version: "3"
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./pass-validator:/var/www/pass-validator
    links:
      - php
    networks:
      - bridge

  php:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./pass-validator:/var/www/pass-validator
    networks:
      - bridge

networks:
  bridge:
    driver: bridge